import '@/styles/globals.css'
import Head from 'next/head'


export default function App({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>CS Profile</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icon-2.png" />
        <link rel="apple-touch-icon" href="/images/icon-2.png" />
        <meta name='keywords' content='CS, CS Profile, Counter Strike, CS Stats, Counter Strike Stats, Counter Strike Profile, Counter Strike 2, CS2, CS 2, HLTV, KD, Counter Strike Stats, Generate' />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
